### ISSUE TITLE
where is gpu version

### ISSUE THREAD

**Issue by kernel8liang** [bigaidream-projects/drmad#4]
so, where is the gpu version?

**Comment by bigaidream** [comment]
We are planning to release the Theano version early next month.

**Comment by kernel8liang** [comment]
thanks, 

how read your code?

i have read your paper "Drmad",  where the algorithm2 be implemented ?

**Comment by bigaidream** [comment]
https://github.com/bigaidream-projects/drmad/blob/master/cpu_ver/hypergrad/optimizers.py#L403-L439

**Comment by kernel8liang** [comment]
thank you very much.
