### ISSUE TITLE
run "experiments/safe/safe.py" crash

### ISSUE THREAD

**Issue by kernel8liang** [bigaidream-projects/drmad#5]
try to run ```safe.py``` get error below:

```
$ python safe.py
Traceback (most recent call last):
  File "safe.py", line 180, in <module>
    results = run()
  File "safe.py", line 42, in run
    all_data = mnist.load_data_as_dict()
  File "/home/liang/workspace/drmad/cpu_ver/hypergrad/mnist.py", line 55, in load_data_as_dict
    X, T = load_data(normalize)[:2]
  File "/home/liang/workspace/drmad/cpu_ver/hypergrad/mnist.py", line 37, in load_data
    with open(datapath("mnist_data.pkl")) as f:
IOError: [Errno 2] No such file or directory: '/home/jie/d2/bitbucket/hypergradient_bo/data/mnist/mnist_data.pkl'
```

I also tried to run ```cifar10.py```, get error below:

```
$ python cifar10.py
Traceback (most recent call last):
  File "cifar10.py", line 179, in <module>
    results = run()
  File "cifar10.py", line 41, in run
    all_data = mnist.load_data_as_dict()
  File "/home/liang/workspace/drmad/cpu_ver/hypergrad/mnist.py", line 55, in load_data_as_dict
    X, T = load_data(normalize)[:2]
  File "/home/liang/workspace/drmad/cpu_ver/hypergrad/mnist.py", line 37, in load_data
    with open(datapath("mnist_data.pkl")) as f:
IOError: [Errno 2] No such file or directory: '/home/jie/d2/bitbucket/hypergradient_bo/data/mnist/mnist_data.pkl'
```

why run cifar10 will load mnist's data?

**Comment by bigaidream** [comment]
As for MNIST dataset, please download the whole `/data` folder from https://github.com/HIPS/hypergrad

The entry point is `safe.py`, which is similar to `experiment.py` used in https://github.com/HIPS/hypergrad/blob/master/experiments/Feb_3_nn_ard/4_meta_reg/experiment.py

**Comment by bigaidream** [comment]
Sorry for the inconvenience, I will make this repo more self-contained.

**Comment by bigaidream** [comment]
Also you need to specify the data path to your local data: https://github.com/bigaidream-projects/drmad/blob/master/cpu_ver/hypergrad/mnist.py#L11

**Comment by kernel8liang** [comment]
thanks for sharing your work, now i make it running.
i am plan to test it with large net like "resnet" and large data set like imagenet.

**Comment by bigaidream** [comment]
Unfortunately, you cannot run it on ImageNet as the code can only run on CPU at this moment. 
I guess you have to wait for our Theano version, which supports GPU.

**Comment by kernel8liang** [comment]
if you don't mind， i plan to implement the algorithm on mxnet.
mxnet is running in our gpu server.

**Comment by bigaidream** [comment]
That would be great!
If you have any issues/questions, let me know.

**Comment by taineleau-zz** [comment]
@kernel8liang Hi, thank you for your attention. 

As far as I am concerned, I don't think it's trivial to implement it in MXNet (Symbolic Differentiation and/or AD). If you do want to give it a shot, you'd better do it in a symbolic differentiation fashion. I would suggest that you take my advice since one of the contributors of MinPy is my labmate & classmate and we have discussed about it. (FYI, MinPy implemented AD for MXNet, which hasn't supported second order differentiation yet.) 

If it's possible, I plan to make a contribution to MinPy, and thus enable MXNet to support some crucial features for DrMAD. But for now, I would like to stick on the Theano version, which will be released soon. 

Please let me know if you have any question.

Cheers,

Taineleau

**Comment by kernel8liang** [comment]
@taineleau Hi, thanks for your advice.

I will do a more deep investigating on this.

**Comment by kernel8liang** [comment]
@taineleau, @bigaidream  Hi,

I go through details about how to implement DrMAD on Mxnet, it's not easy thing, for a limit time, i may not implement it right now, in future, if you work on this issue, maybe our team could cooperation with you.

i noticed, you are base in shanghai now, if you have time we sincerely invite you to come give us a talk about this issue. we locate at huamu and yanggao road.

-Liang
