### ISSUE TITLE
plot error

### ISSUE THREAD

**Issue by kernel8liang** [bigaidream-projects/drmad#6]
uncomment the ```plot()```, get error.

```
Traceback (most recent call last):
  File "safe.py", line 186, in <module>
    plot()
  File "safe.py", line 161, in plot
    ax = fig.add_subplot(213)
  File "/Users/liang/anaconda/lib/python2.7/site-packages/matplotlib/figure.py", line 1005, in add_subplot
    a = subplot_class_factory(projection_class)(self, *args, **kwargs)
  File "/Users/liang/anaconda/lib/python2.7/site-packages/matplotlib/axes/_subplots.py", line 64, in __init__
    maxn=rows*cols, num=num))
ValueError: num must be 1 <= num <= 2, not 3
```

**Comment by bigaidream** [comment]
https://github.com/bigaidream-projects/drmad/blob/master/cpu_ver/experiments/exp1/safe/safe.py

**Comment by kernel8liang** [comment]
any detail ?

**Comment by bigaidream** [comment]
In that script, I didn't use `plot()`.

**Comment by kernel8liang** [comment]
which script ```plot()``` figures in the paper, i want reproduce the experiment first.

**Comment by kernel8liang** [comment]
the experiment in the paper is for regularization， have you do some experiments on learning rate?

**Comment by bigaidream** [comment]
Haven't tested.

**Comment by kernel8liang** [comment]
is there a script can ```plot()``` figures in the paper ?

**Comment by bigaidream** [comment]
https://github.com/bigaidream-projects/drmad/tree/master/cpu_ver/tests

**Comment by kernel8liang** [comment]
ok, i will try that one.

**Comment by kernel8liang** [comment]
i tried both ```plot_2()``` and ```plot_3()```.  both of them didn't work.


```
python plot_3.py
Traceback (most recent call last):
  File "plot_3.py", line 200, in <module>
    plot()
  File "plot_3.py", line 121, in plot
    with open('results.pkl') as f:
IOError: [Errno 2] No such file or directory: 'results.pkl'
```

the ```run``` function which seems can produce the ```results.pkl``` in the file is not work too.

and i read the code in the ```exp1/safe``` , you using the same mini-batch to train 10000 times, i think it's not work.

so, could you give a prosedue with the code i can reproduce your experiment in your paper?

**Comment by bigaidream** [comment]
Please note that, I didn't change the training procedure used in https://github.com/HIPS/hypergrad/blob/master/hypergrad/

I only changed https://github.com/HIPS/hypergrad/blob/master/hypergrad/optimizers.py#L253-L282

**Comment by bigaidream** [comment]
As for `plot_2()`, you need to first train to produce `results.pkl`, as you can see in the code.

**Comment by kernel8liang** [comment]
but the when uncomment the ```run``` function in ```plot_2```, it will get another error.

**Comment by bigaidream** [comment]
To verify the effectiveness, you can just observe the validation error after every meta-iteration. 

I don't remember where is the plotting function used in the paper.

**Comment by kernel8liang** [comment]
ok.
