### ISSUE TITLE
请教版主，drmad 能否优化tensorflow的模型的超参？如何进行?或者代码需要重新按照tensorflow的重写？

### ISSUE THREAD

**Issue by hbyido** [bigaidream-projects/drmad#9]
请教版主，drmad 能否优化tensorflow的模型的超参？如何进行?或者代码需要重新按照tensorflow的重写？

**Comment by bigaidream** [comment]
谢谢你的关注 :)
不能直接用于TensorFlow的模型，需要重写：因为现在基于Theano的框架无法得知TensorFlow模型的computational graph，也就更无法拿到gradients以及hypergradients了。

---

但是我没有用drmad跑超过20000 iterations，所以如果你想用它在某些实际的项目中（比如要跑ImageNet和ResNet），可能需要做别的改进：比如使用比1D subspace更加复杂的投影方法。
我的文章和代码只能验证，至少对于中等规模的模型(包括MLP和CNN)和数据集，drmad这种非对称的back propagation是可行的。
